name: 'Setup'

inputs:
  npm-token:
    description: 'NPM token for authentication'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '22.21.1'
        cache: 'pnpm'

    - name: Setup NPM authentication
      if: inputs.npm-token != ''
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

    - name: Install dependencies
      shell: bash
      run: pnpm --filter=!playground install

    - name: Build packages
      shell: bash
      run: pnpm --filter=motia build

