name: 'Setup'
description: 'Setup Node.js, pnpm, and install dependencies for the motia-js workspace'

inputs:
  npm-token:
    description: 'NPM token for authentication'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '22.21.1'
        cache: 'pnpm'
        cache-dependency-path: motia-js/pnpm-lock.yaml

    - name: Setup NPM authentication
      if: inputs.npm-token != ''
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> motia-js/.npmrc

    - name: Install dependencies
      shell: bash
      working-directory: motia-js
      run: pnpm --filter=!playground install

    - name: Build packages
      shell: bash
      working-directory: motia-js
      run: pnpm --filter=motia build
