import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    index: './src/index.ts',
    workbench: './src/workbench.ts',
    cli: './src/cli.ts',
  },
  format: 'esm',
  platform: 'node',
  external: [
    // Workspace dependencies
    '@motiadev/core',
    '@motiadev/stream-client-node',
    '@motiadev/workbench',
    // npm dependencies
    '@amplitude/analytics-node',
    '@amplitude/analytics-types',
    'antlr4ts',
    'archiver',
    'axios',
    'chokidar',
    'colors',
    'commander',
    'cron',
    'dotenv',
    'esbuild',
    'express',
    'tsx',
    'glob',
    'inquirer',
    'node-cron',
    'openapi-types',
    'python-ast',
    'table',
    'ts-node',
    'typescript',
    'typescript-transform-paths',
    // Node built-ins
    'path',
    'fs',
    'child_process',
    'os',
    'util',
    'stream',
    'events',
    'http',
    'https',
    'url',
    'crypto',
    'buffer',
    'zlib',
    'net',
    'node:path',
    'fs/promises',
    'readline',
  ],
  dts: {
    build: true,
  },
  clean: true,
  outDir: 'dist',
  sourcemap: true,
  unbundle: true,
})
