# Aider Configuration for Motia Projects
# https://aider.chat/docs/config.html

# Read AGENTS.md for project overview and guide references
read: 
  - AGENTS.md
  # Uncomment specific guides as needed for more context:
  # - .cursor/rules/motia/api-steps.mdc
  # - .cursor/rules/motia/event-steps.mdc
  # - .cursor/rules/motia/cron-steps.mdc
  # - .cursor/rules/motia/state-management.mdc
  # - .cursor/rules/motia/middlewares.mdc
  # - .cursor/rules/motia/realtime-streaming.mdc
  # - .cursor/rules/motia/virtual-steps.mdc
  # - .cursor/rules/motia/ui-steps.mdc
  # - .cursor/architecture/architecture.mdc
  # - .cursor/architecture/error-handling.mdc

# Note: AGENTS.md references all detailed guides in .cursor/rules/
# The AI will read those guides when needed based on AGENTS.md instructions

# Auto-commit changes (optional, uncomment to enable)
# auto-commits: true

# Model selection (uncomment your preferred model)
# model: gpt-4
# model: claude-3-5-sonnet-20241022

# Additional context files (optional)
# read:
#   - config.yml
#   - package.json
