name: 'III Engine'
description: 'Start the III Engine via Docker for integration tests'

inputs:
  image:
    description: 'Docker image for the III Engine'
    required: false
    default: 'iiidev/iii:build-amd64'
  config-path:
    description: 'Path to the engine config YAML file (relative to workspace root)'
    required: false
    default: '.github/actions/iii-engine/config-test.yaml'
  health-check-port:
    description: 'Port to health-check for readiness'
    required: false
    default: '3199'
  health-check-retries:
    description: 'Number of health check attempts (2s interval)'
    required: false
    default: '30'

runs:
  using: composite
  steps:
    - name: Start III Engine
      id: start
      shell: bash
      run: |
        docker run -d \
          --name iii-engine \
          --network=host \
          -v "${{ github.workspace }}/${{ inputs.config-path }}":/app/config.yaml:ro \
          -e RUST_LOG=info \
          "${{ inputs.image }}"

        echo "Waiting for III Engine on port ${{ inputs.health-check-port }}..."
        for i in $(seq 1 ${{ inputs.health-check-retries }}); do
          if nc -z 127.0.0.1 ${{ inputs.health-check-port }} 2>/dev/null; then
            echo "III Engine is ready!"
            exit 0
          fi
          echo "  attempt $i/${{ inputs.health-check-retries }}..."
          sleep 2
        done
        echo "Engine did not become ready. Logs:"
        docker logs iii-engine
        exit 1
