name: 'III Engine'
description: 'Start the III Engine via Docker Compose for integration tests'

inputs:
  compose-file:
    description: 'Path to the docker-compose file (relative to workspace root)'
    required: false
    default: 'motia-py/packages/motia/tests/fixtures/docker-compose.yml'

runs:
  using: composite
  steps:
    - name: Start III Engine
      id: start
      shell: bash
      run: |
        docker compose -f "${{ github.workspace }}/${{ inputs.compose-file }}" up -d --wait
