api:
  port: 3000
  paths:
    /api/openai:
      method: POST
      emits: call-openai
    /api/hybrid-endpoint-example:
      method: POST
      emits: hybrid.received
    /api/wistro-server-example:
      method: POST
      emits: ws-server-example.trigger
    /api/endpoint-server-handshake:
      method: POST
      emits: handshake.initiate
    /api/parallel-merge:
      method: POST
      emits: pms.initialize
    /api/dbz/initialize:
      method: POST
      emits: dbz.initialize
    /api/dbz/search-upgrades:
      method: POST
      emits: dbz.evaluate-upgrades
state:
  adapter: redis
  host: localhost
  port: 6379
  password: pingpong