name: E2E Tests

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version being tested'
        required: true
      tag_name:
        description: 'Git tag name'
        required: true
      triggered_by:
        description: 'Run ID that triggered this workflow'
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      result: ${{ steps.test_result.outputs.result }}
    env:
      CI: true
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install pre-release packages globally
        run: |
          npm install -g @motiadev/core@${{ github.event.inputs.version }} --tag pre-release
          npm install -g @motiadev/test@${{ github.event.inputs.version }} --tag pre-release
          npm install -g motia@${{ github.event.inputs.version }} --tag pre-release

      - name: Install E2E dependencies and browsers
        run: |
          cd packages/e2e
          pnpm install
          pnpm exec playwright install
          pnpm exec playwright install-deps

      - name: Clean previous test artifacts
        run: |
          cd packages/e2e
          pnpm clean
          
      - name: Kill any existing processes
        run: |
          pkill -f "motia" || true
          pkill -f "npm run dev" || true
          pkill -f "node.*3000" || true

      - name: Verify Motia CLI installation
        run: |
          which motia || echo "Motia CLI not found in PATH"
          npx motia --version || echo "Motia CLI version check failed"
          node --version
          npm --version
          
      - name: Run E2E tests
        id: run_tests
        env:
          MOTIA_VERSION: ${{ github.event.inputs.version }}
        run: |
          cd packages/e2e
          echo "Starting E2E tests with Motia version: $MOTIA_VERSION"
          pnpm test:e2e --reporter=line,html,github
        continue-on-error: true

      - name: Set test result
        id: test_result
        run: |
          echo "Test outcome: ${{ steps.run_tests.outcome }}"
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            echo "result=success" >> $GITHUB_OUTPUT
            echo "✅ E2E tests passed successfully"
          else
            echo "result=failure" >> $GITHUB_OUTPUT
            echo "❌ E2E tests failed"
            echo "Check the test results and logs for details"
            exit 1
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ github.event.inputs.version }}
          path: |
            packages/e2e/playwright-report/
            packages/e2e/test-results/
          retention-days: 30

  trigger-next-step:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MOTIA_CI_APP_ID }}
          private-key: ${{ secrets.MOTIA_CI_APP_PRIVATE_KEY }}

      - name: Trigger finalize release (on success)
        if: needs.e2e-tests.outputs.result == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'finalize-release.yml',
              ref: 'main',
              inputs: {
                version: '${{ github.event.inputs.version }}',
                tag_name: '${{ github.event.inputs.tag_name }}',
                triggered_by: '${{ github.event.inputs.triggered_by }}'
              }
            });

      - name: Trigger rollback (on failure)
        if: needs.e2e-tests.outputs.result == 'failure'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'rollback-release.yml',
              ref: 'main',
              inputs: {
                version: '${{ github.event.inputs.version }}',
                tag_name: '${{ github.event.inputs.tag_name }}',
                triggered_by: '${{ github.event.inputs.triggered_by }}',
                reason: 'E2E tests failed'
              }
            }); 